on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Yarn install
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install --cwd example --frozen-lockfile
    - run: yarn install --frozen-lockfile
    - run: yarn typescript
    - run: yarn lint
