name: Prepare release

on:
  pull_request:
    types: [ labeled ]
    branches:
      - master

jobs:
  prepare-release:
    name: Prepare release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get current version
        run: |
          CURRENT_VERSION=$(npm view @prolaxu/pusher-websocket-react-native version)
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV
      - uses: actions/checkout@v2
        with:
          repository: pusher/actions
          token: ${{ secrets.PUSHER_CI_GITHUB_PRIVATE_TOKEN }}
          path: .github/actions
      - uses: ./.github/actions/prepare-version-bump
        id: bump
        with:
          current_version: ${{ env.CURRENT_VERSION }}
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: yarn install
      - name: Push
        shell: bash
        run: |
          echo "$(jq '.version = "${{ steps.bump.outputs.new_version }}"' package.json)" > package.json

          git add package.json CHANGELOG.md
          git commit -m "Bump to version ${{ steps.bump.outputs.new_version }}"
          git push
